Algoritmo "43-expressões"
// Disciplina   : [Lógica de Programação e Javascript]
// Professor   : Jailson Costa dos Santos 
// Descrição   : Para A = V, B = V e C = F, qual o resultado da avaliação das seguintes expressões
// Autor(a)    : Jean da Costa Silva
// Data atual  : 27/08/2021
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo