Algoritmo "semnome"
// Disciplina   : [Lógica de Programação e Javascript]
// Professor   : Jailson
// Descrição   : Exibir uma mensagem
// Autor(a)    : Jean da Costa Silva
// Data atual  : 24/08/2021
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval ("Jailson - Osasco")
Escreval ("Equipe 04")
Escreval ("Abner")

Fimalgoritmo