Algoritmo "Exibir mensagem"
// Disciplina   : [Lógica de Programação e JavaScript]
// Professor   : Jailson
// Descrição   : Exibir uma mensagem
// Autor(a)    : Jean
// Data atual  : 24/08/2021
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval ("Jean - Perus")
Escreval ("Equipe 04")
Escreval ("Juan")

Fimalgoritmo