Algoritmo "Sucessor"
// Disciplina   : [Lógica de Programação e Javascript]
// Professor   : Jailson
// Descrição   : Descobre o sucessor de um número atrávez de uma multiplicação
// Autor(a)    : Jean da Costa Silva
// Data atual  : 24/08/2021
Var
valor:inteiro
sucessor:inteiro
Inicio
Escreva ("digite um número: ")
leia (valor)
sucessor <- valor + 1
escreva ("O antecessor de",valor," é: ",sucessor)


Fimalgoritmo